from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any


class ConfigError(RuntimeError):
    """Raised when application configuration is missing or invalid."""


@dataclass(frozen=True)
class AppSettings:
    name: str
    environment: str
    base_url: str
    session_secret: str
    cookie_secure: bool
    trusted_hosts: tuple[str, ...]


@dataclass(frozen=True)
class StorageSettings:
    database_path: Path
    resume_dir: Path
    max_upload_mb: int
    allowed_extensions: tuple[str, ...]


@dataclass(frozen=True)
class AdminSettings:
    username: str
    password_hash: str


@dataclass(frozen=True)
class SecuritySettings:
    application_limit_per_hour: int
    login_limit_per_15_minutes: int


@dataclass(frozen=True)
class AISettings:
    enabled: bool
    provider: str
    base_url: str
    endpoint_path: str
    api_key_env: str
    model: str
    timeout_seconds: int
    max_resume_characters: int


@dataclass(frozen=True)
class Settings:
    app: AppSettings
    storage: StorageSettings
    admin: AdminSettings
    security: SecuritySettings
    ai: AISettings
    config_path: Path


_ENV_PATTERN = re.compile(r"\$\{([A-Z][A-Z0-9_]*)\}")


def _expand_env(value: Any) -> Any:
    if isinstance(value, dict):
        return {key: _expand_env(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_expand_env(item) for item in value]
    if not isinstance(value, str):
        return value

    def replace(match: re.Match[str]) -> str:
        name = match.group(1)
        if name not in os.environ:
            raise ConfigError(f"Required environment variable is not set: {name}")
        return os.environ[name]

    return _ENV_PATTERN.sub(replace, value)


def _require(mapping: dict[str, Any], key: str, section: str) -> Any:
    if key not in mapping:
        raise ConfigError(f"Missing configuration value: {section}.{key}")
    return mapping[key]


def _resolve_path(raw: str, config_dir: Path) -> Path:
    path = Path(raw).expanduser()
    if not path.is_absolute():
        path = config_dir / path
    return path.resolve()


def load_settings(config_path: str | Path | None = None) -> Settings:
    selected = Path(
        config_path
        or os.environ.get("BITE_HUNT_CONFIG", "config/config.local.json")
    ).expanduser().resolve()
    if not selected.is_file():
        raise ConfigError(
            f"Configuration file not found: {selected}. "
            "Copy config/config.example.json or run scripts/render_config.py."
        )

    try:
        raw = json.loads(selected.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ConfigError(f"Unable to read configuration: {exc}") from exc

    raw = _expand_env(raw)
    app = raw.get("app", {})
    storage = raw.get("storage", {})
    admin = raw.get("admin", {})
    security = raw.get("security", {})
    ai = raw.get("ai", {})
    config_dir = selected.parent

    session_secret = str(_require(app, "session_secret", "app"))
    if len(session_secret) < 32 or session_secret.startswith("CHANGE_ME"):
        raise ConfigError("app.session_secret must be a random value of at least 32 characters")

    password_hash = str(_require(admin, "password_hash", "admin"))
    if not password_hash.startswith("scrypt$"):
        raise ConfigError("admin.password_hash must be generated by scripts/render_config.py")

    max_upload_mb = int(storage.get("max_upload_mb", 10))
    if not 1 <= max_upload_mb <= 50:
        raise ConfigError("storage.max_upload_mb must be between 1 and 50")

    extensions = tuple(
        str(item).lower().lstrip(".")
        for item in storage.get("allowed_extensions", ["pdf", "doc", "docx"])
    )
    supported = {"pdf", "doc", "docx"}
    if not extensions or not set(extensions).issubset(supported):
        raise ConfigError("storage.allowed_extensions may only contain pdf, doc, and docx")

    endpoint_path = str(ai.get("endpoint_path", "/chat/completions"))
    if not endpoint_path.startswith("/"):
        raise ConfigError("ai.endpoint_path must start with /")

    return Settings(
        app=AppSettings(
            name=str(app.get("name", "Bite Hunt Careers")),
            environment=str(app.get("environment", "production")),
            base_url=str(app.get("base_url", "http://localhost")),
            session_secret=session_secret,
            cookie_secure=bool(app.get("cookie_secure", False)),
            trusted_hosts=tuple(app.get("trusted_hosts", ["*"])),
        ),
        storage=StorageSettings(
            database_path=_resolve_path(
                str(_require(storage, "database_path", "storage")), config_dir
            ),
            resume_dir=_resolve_path(
                str(_require(storage, "resume_dir", "storage")), config_dir
            ),
            max_upload_mb=max_upload_mb,
            allowed_extensions=extensions,
        ),
        admin=AdminSettings(
            username=str(_require(admin, "username", "admin")),
            password_hash=password_hash,
        ),
        security=SecuritySettings(
            application_limit_per_hour=max(
                1, int(security.get("application_limit_per_hour", 8))
            ),
            login_limit_per_15_minutes=max(
                1, int(security.get("login_limit_per_15_minutes", 10))
            ),
        ),
        ai=AISettings(
            enabled=bool(ai.get("enabled", False)),
            provider=str(ai.get("provider", "openai_compatible")),
            base_url=str(ai.get("base_url", "https://api.openai.com/v1")).rstrip("/"),
            endpoint_path=endpoint_path,
            api_key_env=str(ai.get("api_key_env", "BITE_HUNT_AI_API_KEY")),
            model=str(ai.get("model", "")),
            timeout_seconds=max(5, min(180, int(ai.get("timeout_seconds", 60)))),
            max_resume_characters=max(
                2_000, min(100_000, int(ai.get("max_resume_characters", 30_000)))
            ),
        ),
        config_path=selected,
    )

